<?php
/*
 * AdvancedAstrologyAndHoroscopeLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 05/19/2015
 */

namespace AdvancedAstrologyAndHoroscopeLib;

class Configuration {
    //The base Uri for API calls
    const BASEURI = 'https://vedicrishi-horoscope-and-astrology-v1.p.mashape.com';

    //The username to use with basic authentication
    //TODO: Replace the basicAuthUserName with an appropriate value
    public static $basicAuthUserName = 'TODO: Replace';

    //The password to use with basic authentication
    //TODO: Replace the basicAuthPassword with an appropriate value
    public static $basicAuthPassword = 'TODO: Replace';

}
